# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 14:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('id_proof', models.FileField(upload_to='id_proof/')),
                ('photo', models.FileField(upload_to='photos/')),
                ('user_type', models.CharField(choices=[('f', 'Farmer'), ('u', 'Consumer')], default='u', max_length=1)),
                ('shares', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('total_quantity', models.FloatField()),
                ('quantity_remaining', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='CropPurchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchased_quantity', models.FloatField()),
                ('purchase_value', models.FloatField()),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smart_contract_app.Crop')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Land',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=30)),
                ('size', models.IntegerField()),
                ('unit', models.CharField(choices=[('m2', 'm. sq'), ('km2', 'km. sq'), ('he', 'hectare')], default='m2', max_length=2)),
                ('duration', models.IntegerField()),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smart_contract_app.AppUser')),
            ],
        ),
        migrations.CreateModel(
            name='SharePurchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('transaction_id', models.CharField(max_length=32)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='crop',
            name='crop_land',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smart_contract_app.Land'),
        ),
    ]
