# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_contract_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='id_proof',
            field=models.FileField(blank=True, upload_to='id_proof/'),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='photo',
            field=models.FileField(blank=True, upload_to='photos/'),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='shares',
            field=models.IntegerField(default=0),
        ),
    ]
